# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imgURL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='videoURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
