# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160921_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(default='Resumen del post'),
            preserve_default=False,
        ),
    ]
